# Generated by Django 3.2.8 on 2021-10-29 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_userkyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkyc',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='xml_raw_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
