# Generated by Django 3.2.8 on 2021-10-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkyc',
            old_name='xml_file',
            new_name='zip_file',
        ),
    ]
