# Generated by Django 3.2.8 on 2021-10-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantrequesttolandlord',
            name='request_approved',
            field=models.BooleanField(default=True),
        ),
    ]
