# Generated by Django 3.2.8 on 2021-10-29 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20211030_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='line_1',
            new_name='house',
        ),
        migrations.RemoveField(
            model_name='address',
            name='line_2',
        ),
        migrations.RemoveField(
            model_name='userrentedaddress',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='address_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postOffice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='subDistrict',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantrequesttolandlord',
            name='request_completed_by_tenant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrentedaddress',
            name='original_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original', to='address.address'),
        ),
        migrations.AddField(
            model_name='userrentedaddress',
            name='rented_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented', to='address.address'),
        ),
        migrations.AlterField(
            model_name='tenantrequesttolandlord',
            name='request_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenantrequesttolandlord',
            name='request_approved_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
