# Generated by Django 3.2.8 on 2021-10-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20211030_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrequesttolandlord',
            name='request_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantrequesttolandlord',
            name='request_declined_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
