# Generated by Django 3.2.8 on 2021-10-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_tenantrequesttolandlord_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrequesttolandlord',
            name='request_completed_by_tenant_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
