# Generated by Django 3.1.13 on 2021-10-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_tenantrequesttolandlord_request_completed_by_tenant_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrequesttolandlord',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantrequesttolandlord',
            name='expires_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenantrequesttolandlord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrentedaddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
